### ISSUE TITLE
Add OS X compatibility

### ISSUE THREAD

**Issue by MoOx** [putaindecode/sharedrop#2]
- [x] terminal-notifier
- [x] [fswatch](http://stackoverflow.com/questions/1515730/is-there-a-command-like-watch-or-inotifywait-on-the-mac)
- [x] convert

**Comment by madx** [comment]
Yes!

**Comment by Macxim** [comment]
:+1:

**Comment by MoOx** [comment]
I just miss a `convert` equivalent for now. Any alternative ?

**Comment by madx** [comment]
Have you tried to install ImageMagick or GraphicsMagick from brew? They should provide the convert program

**Comment by MoOx** [comment]
Ah, hum ok :)

**Comment by MoOx** [comment]
It's ok with imagemagick

**Comment by madx** [comment]
Great then :)

I'm leaving the issue open until you confirm that everything works

**Comment by MoOx** [comment]
Will close from a PR ;)

**Comment by MoOx** [comment]
What do you think about only using fswatch ?

**Comment by madx** [comment]
I have to test how it works and I'm likely to use it since it provibes better cross-compatibility than inotifywait

**Comment by MoOx** [comment]
I will push a PR when it's so you can  test it before blind merge :)
