### ISSUE TITLE
Add support for alternative to rsync

### ISSUE THREAD

**Issue by MoOx** [putaindecode/sharedrop#6]
On my gandi simple hosting I cannot use rsync yet :/
lftp seems a good alternative to handle that.

**Comment by madx** [comment]
I just pushed a fix so you can override the command in your config file

Just redefine the `sync_command` function like you want. It's not pretty yet but it works :)

**Comment by MoOx** [comment]
Maybe we should introduce alternative in the code directly (so others people can reuse those) ?
